version: '3.5'
services:
 crdb:
   image: crdbnet
   ports:
     - 26257:26257
     - 8080:8080
   command: start-single-node --insecure
   cap_add:
     - NET_ADMIN

 prom:
   image: prom/prometheus
   ports:
     - 9090:9090
   volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
     - ./alerts.rules.yml:/etc/prometheus/rules/alerts.rules.yml
     - ./alerts.rules.yml:/etc/prometheus/rules/aggregation.rules.yml

 alert:
   image: prom/alertmanager
   ports:
     - 9093:9093
   command:
      - '--config.file=/prometheus/alertmanager.yml'
   volumes:
     - ./alertmanager-config.yml:/prometheus/alertmanager.yml

 grafana:
   image: grafana/grafana
   ports:
     - 3000:3000
